version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: oj-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: oj
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: oj-redis
    restart: always
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  oj-nest:
    build: .
    container_name: oj-nest
    restart: always
    ports:
      - '8080:8080'
    environment:
      PORT: 8080
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 1234
      DB_DATABASE: oj
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ''
      REDIS_DB: 0
      JUDGE0_BASE_URL: http://judge0-v1131-extra-server-1:2358
      TOKEN_TTL: 3600
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  mysql_data:
  redis_data:
